name: corretor_news
description: Corretor News App - O app do Corretor de Imóveis

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+1.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  auto_size_text_pk: ^3.0.0
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_device_type: ^0.4.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  launch_review: ^3.0.1
  lint: ^1.7.2
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  provider: ^6.0.0
  responsive_framework: ^0.1.4
  salomon_bottom_bar: ^3.1.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.12

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  # change_app_package_name: ^1.0.0
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  

  flutter_icons:
  android: "launcher_icon"
  ios: false
  android: true
  image_path: "assets/icon/icon.png"
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/coin/
    - assets/intro/
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
